import pandas_datareader.data as web
import pandas as pd
from datetime import datetime
import matplotlib.pyplot as plt
import sqlite3
import os

os.chdir(r'D:\myprojects\TradingDB')

#tickers.txt contains all ticker list as a string format:
# "['1234', '1243', '5423', ...., '7328']"
#tickers.txt is generated by the following script: stock_list is a dictionary.
# with open('stocklist.json', 'w') as file:
#     json.dump(stock_list, file)
# with open('tickers.txt', 'w') as file:
#     file.write(str(list(stock_list['tickerkeys'].keys())))

with open('tickers.txt', 'r') as file:
    tickers = file.read()
tickers = [ticker.strip(' \'[]\"') for ticker in tickers.split(',')]
start = datetime(2021, 1, 1)
end = datetime.today()

for ticker in tickers:
    df = web.DataReader(ticker, 'naver', start, end)
    df = df.astype('float64')
    with sqlite3.connect(ticker+'.db') as file:
        df.to_sql('Daily_Prices', file)
